import {
  LayoutDashboard, Users, Package, Truck, ShoppingBag, BarChart3,
  ShoppingCart, BarChart2, User, Calendar, Wrench, Star, Clock,
} from 'lucide-react'

// Per-role layout configuration. Full Tailwind class strings are stored
// here (not interpolated) so the JIT compiler can see every class.
export const ROLES = {
  admin: {
    label: 'Administrator',
    roleTag: 'Admin',
    sidebarBg: 'bg-[#0f0f0f]',
    brandText: 'text-white',
    brandSub: 'text-white/40',
    divider: 'bg-white/[0.06]',
    asideBorder: 'border-white/[0.04]',
    brandTile: 'bg-white text-black shadow-[0_0_12px_rgba(255,255,255,0.12)]',
    navActive: 'bg-white/[0.1] text-white',
    navIdle: 'text-zinc-500 hover:text-zinc-200 hover:bg-white/[0.05]',
    navIconActive: 'text-white',
    navIconIdle: 'text-zinc-600 group-hover:text-zinc-300',
    indicator: 'bg-white',
    avatar: 'bg-gradient-to-br from-zinc-600 to-zinc-800 text-white ring-white/10',
    userName: 'text-zinc-200',
    userMail: 'text-zinc-600',
    bottomText: 'text-zinc-500 hover:text-zinc-200 hover:bg-white/[0.05]',
    signOut: 'text-zinc-600 hover:text-red-400 hover:bg-red-500/10',
    statusDot: 'bg-emerald-500 ring-emerald-500/25',
    contentMax: 'max-w-7xl',
    nav: [
      { to: '/admin/dashboard', label: 'Dashboard', icon: LayoutDashboard },
      { to: '/admin/staff', label: 'Staff', icon: Users },
      { to: '/admin/parts', label: 'Parts', icon: Package },
      { to: '/admin/vendors', label: 'Vendors', icon: Truck },
      { to: '/admin/purchase-invoices', label: 'Purchase Invoices', icon: ShoppingBag },
      { to: '/admin/reports', label: 'Reports', icon: BarChart3 },
      { to: '/admin/reviews', label: 'Reviews', icon: Star },
    ],
  },

  staff: {
    label: 'Staff',
    roleTag: 'Staff',
    sidebarBg: 'bg-[#061a0e]',
    brandText: 'text-white',
    brandSub: 'text-white/40',
    divider: 'bg-white/[0.06]',
    asideBorder: 'border-white/[0.04]',
    brandTile: 'bg-emerald-500 text-white shadow-[0_0_16px_rgba(16,185,129,0.3)]',
    navActive: 'bg-emerald-500/20 text-emerald-300',
    navIdle: 'text-emerald-700 hover:text-emerald-200 hover:bg-emerald-500/10',
    navIconActive: 'text-emerald-400',
    navIconIdle: 'text-emerald-800 group-hover:text-emerald-400',
    indicator: 'bg-emerald-400',
    avatar: 'bg-emerald-900 text-emerald-300 ring-emerald-700',
    userName: 'text-emerald-200',
    userMail: 'text-emerald-900',
    bottomText: 'text-emerald-700 hover:text-emerald-200 hover:bg-emerald-500/10',
    signOut: 'text-emerald-800 hover:text-red-400 hover:bg-red-500/10',
    statusDot: 'bg-emerald-500 ring-emerald-500/25',
    contentMax: 'max-w-7xl',
    nav: [
      { to: '/staff/dashboard', label: 'Dashboard', icon: LayoutDashboard },
      { to: '/staff/customers', label: 'Customers', icon: Users },
      { to: '/staff/sales', label: 'Sales', icon: ShoppingCart },
      { to: '/staff/appointments', label: 'Appointments', icon: Calendar },
      { to: '/staff/part-requests', label: 'Part Requests', icon: Wrench },
      { to: '/staff/customer-reports', label: 'Customer Reports', icon: BarChart2 },
      { to: '/staff/profile', label: 'My Profile', icon: User },
    ],
  },

  customer: {
    label: 'Customer Portal',
    roleTag: 'Customer',
    sidebarBg: 'bg-white dark:bg-zinc-900',
    brandText: 'text-gray-900 dark:text-white',
    brandSub: 'text-gray-400 dark:text-zinc-500',
    divider: 'bg-gray-200/70 dark:bg-zinc-800',
    asideBorder: 'border-gray-200 dark:border-zinc-800',
    brandTile: 'bg-indigo-600 text-white shadow-[0_2px_10px_rgba(79,70,229,0.35)]',
    navActive: 'bg-indigo-50 text-indigo-700 dark:bg-indigo-500/15 dark:text-indigo-300',
    navIdle: 'text-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-zinc-400 dark:hover:text-white dark:hover:bg-zinc-800',
    navIconActive: 'text-indigo-600 dark:text-indigo-400',
    navIconIdle: 'text-gray-400 group-hover:text-gray-600 dark:text-zinc-500 dark:group-hover:text-zinc-300',
    indicator: 'bg-indigo-600 dark:bg-indigo-400',
    avatar: 'bg-indigo-100 text-indigo-700 ring-indigo-200 dark:bg-indigo-500/20 dark:text-indigo-300 dark:ring-indigo-500/30',
    userName: 'text-gray-900 dark:text-white',
    userMail: 'text-gray-400 dark:text-zinc-500',
    bottomText: 'text-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-zinc-400 dark:hover:text-white dark:hover:bg-zinc-800',
    signOut: 'text-gray-500 hover:text-red-600 hover:bg-red-50 dark:text-zinc-400 dark:hover:text-red-400 dark:hover:bg-red-500/10',
    statusDot: 'bg-indigo-500 ring-indigo-500/25',
    contentMax: 'max-w-5xl',
    nav: [
      { to: '/customer/dashboard', label: 'My Profile', icon: User },
      { to: '/customer/catalog', label: 'Browse Parts', icon: Package },
      { to: '/customer/appointments', label: 'Appointments', icon: Calendar },
      { to: '/customer/part-requests', label: 'Part Requests', icon: Wrench },
      { to: '/customer/reviews', label: 'Reviews', icon: Star },
      { to: '/customer/history', label: 'History', icon: Clock },
    ],
  },
}
